
X_customer = {"Gender": "Male",
              "Customer Type": "Loyal Customer",
              "Age": 55,
              "Type of Travel": "Business travel",
              "Class": "Eco",
              "Flight Distance": 100,
              "Inflight wifi service": 2,
              "Departure/Arrival time convenient": 1,
              "Ease of Online booking": 1,
              "Gate location": 1,
              "Food and drink": 2,
              "Online boarding": 2,
              "Seat comfort": 2,
              "Inflight entertainment": 2,
              "On-board service": 5,
              "Leg room service": 3,
              "Baggage handling": 2,
              "Checkin service": 3,
              "Inflight service": 3,
              "Cleanliness": 2,
              "Departure Delay in Minutes": 600,
              "Arrival Delay in Minutes": 8.0}